### ISSUE TITLE
Updating "definitions" (deprecated) to "$defs" in some Json schemas

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-v2#153]
Some Json files include the "defnitions" element.
In Json schema '2020-12' it has been deprecated to "$defs".
VS Code validator, at least, is complaining about that.

@mbaudis should I edit the json version directly or should the source generator from YAML?
(I haven't spotted the place on it)

**Comment by mbaudis** [comment]
@jrambla I'll do. The "some" adds up since it's not only the `definitions:` but also the references to them e.g. `#/definitions/ResultsetInstance` ... I'll change & make a PR for review.

Re editing: Yes, YAML version and then local use of `bin/vamlerRunner.sh' which I wrote for *locally performed* schema conversion. It uses a function to keep the json parameters in order; when editing by hand this might lead to changed files which git wants to update then (purely due to changed order).

**Comment by jrambla** [comment]
@mbaudis is this done and could we close the issue?

**Comment by mbaudis** [comment]
@jrambla This was addressed in https://github.com/ga4gh-beacon/beacon-v2/pull/155 - but this hadn't been merged since missing a review ...

**Comment by costero-e** [comment]
Closing as this has been merged in #155.
