### ISSUE TITLE
models.md diagram has some errors

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-v2#17]
The current Model only describes `Individuals `inside `cohorts `and `genomicVariantions `inside `datasets`. The relationships from `dataset ` to any other entry type are not defined. Neither between `individuals `and `datasets`. Except for cases where a `dataset `is for `biosamples `(no `individuals `in that Beacon instance), that approach was simpler. `Datasets `> `Biosamples `use case is something we would probably need to add to the Model itself.

**Comment by mbaudis** [comment]
@jrambla I've changed the diagram. But in my understanding of "how it should be":
- an individual w/ its biosamples and the case level variants is owned by the dataset; this is the normal way AFAIK (think TCGA or whatever study/dataset; i.e. you ask a DAC for the data bundle)
- `genomicVariations` _could_ be part of a dataset, but this limits the utility since the same canonical variant will pop up or be queried for several places
- `cohorts` are logically the same as `datasets`, logistically different since they may be composed of objects from one or several datasets

For many implementations it won't make a big difference since they either treat all datasets as separate entities with varying content (from full document stack to only variants or biosamples etc.); but for the ideal world of dynamic cohorts etc. I'm not sure how this can easily be modelled. One could think about a structure where the `genomicVariations` in their current form are owned by the Beacon, and then have the separation w/ the `caseLevelData` (i.e. variant instances) as part of the datasets... But I'm not pushing anything here; we ourselves just keep all in separate datasets...

**Comment by mbaudis** [comment]
``` mermaid
classDiagram

    analyses <-- genomicVariations : 1..n
    runs <-- analyses : 1..n
    biosamples <-- runs : 1..n
    individuals <-- biosamples : 1..n

    runs <.. genomicVariations : 1..n
    biosamples <.. genomicVariations : 1..n
    individuals <.. genomicVariations : 1..n
    biosamples <.. analyses : 1..n
    individuals <.. analyses : 1..n
    individuals <.. runs : 1..n

    cohorts o-- individuals : 1..n
    datasets o-- genomicVariations : 1..n

    class genomicVariations{
        analysisId
        runId
        biosampleId
        individualId
        variation
        clinicalInterpretations
        caseLevelData
        ...
    }
    class analyses{
        id
        runId
        biosampleId
        individualId
        analysisDate
        pipelineName
        aligner
        ...
    }
    class biosamples{
        id
        individualId
        biosampleStatus
        sampleOriginType
        histologicalDiagnosis
        collectionDate
        ...
    }
    class individuals{
        id
        sex
        diseases
        phenotypicFeatures
        ethnicity
        pedigrees
        ...
    }
    class runs{
        id
        biosampleId
        individualId
        runDate
        librarySource
        libraryStrategy
        platform
        ...
        }
    class datasets{
        id
        name
        description
        dataUseCondition
        info
        updateDateTime
        ...
    }
    class cohorts{
        id
        name
        cohortType
        cohortSize
        cohortDataTypes
        cohortDesign
        ...
    }
```

**Comment by mbaudis** [comment]
This diagram above can be modified in the source!

**Comment by mbaudis** [comment]
Closing this since original complaint has been addressed, IMO.
