### ISSUE TITLE
Schemas missing $id 

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2#20]
Schemas should have `$id` parameters.

Example: `"$id": https://progenetix.org/services/schemas/BeaconServiceError/v2021-03-07`

**Comment by jrambla** [comment]
@redmitry @datsirul 
I've been confused by the $id in the Json Schemas, the actual usefulness and its compatibility with OA...
Do you have insights or opinions on this topic?

**Comment by redmitry** [comment]
I would be cautious in using "$id" unless we think well the schemas structure.
In JSON schema "$id" is a schema (subschema) context which is used to the "$ref" resolution.
There are MANY ways to use (and resolve) "$ref" in the schema;:
1. absolute URL - "https://myschema.com/schema_file.json"
2. anchor - "#my_anchor_name"
3. relative - "/my_other_schema_file.json"
4. self - "#/$def/my_element"
The problem here is "relative" as it must be resolved against the "$id". So imagine you download the schema locally. the $ref will go to the original site in this case.

We may use relative "$id" so it would be relative to the root, but not sure do we need it and what the gain,

D.

**Comment by jrambla** [comment]
Closing it, as we have no clarity on it and we probably should discuss it in the context of the new GA4GH indentifiers for schemas
