### ISSUE TITLE
Some errors in the documentation

### ISSUE THREAD

**Issue by mshadbolt** [ga4gh-beacon/beacon-v2#42]
Hi, I really appreciate the documentation website, I have found a few bugs here and there that I thought I would make you aware of, not sure if there are some issues with how it is reading information from the schemas?

Here are some examples:
http://docs.genomebeacons.org/schemas-md/cohorts_defaultSchema/

![Screen Shot 2022-07-19 at 9 55 21 am](https://user-images.githubusercontent.com/13007987/179636120-6ef18fdb-6a53-4c30-ac6b-f0a73658f633.png)
`inclusionCriteria` listed as NOT matching

http://docs.genomebeacons.org/schemas-md/obj/eventGenders/

![Screen Shot 2022-07-19 at 9 41 40 am](https://user-images.githubusercontent.com/13007987/179636159-9e1b76e6-064e-469b-9d65-327808405778.png)
`eventGenders` listed as 'geographical information'

**Comment by mbaudis** [comment]
@mshadbolt This is a problem w/ the parser for the inline descriptions, picking the one from the $ref'd object in cases where the referencing object may have its own, more specific. E.g. in the source it is

```
  inclusionCriteria:
    description: >-
      Inclusion criteria used for defining the cohort. It is assumed that
      all cohort participants will match such criteria.
    type: object
    $ref: '#/definitions/CohortCriteria'
```
and
```
  CohortCriteria:
    description: >-
      Criteria used for defining the cohort. It is assumed that all cohort
      participants will match or NOT match such criteria.
    type: object
    properties:
...
```
And in case of `eventGenders` it then uses the erroneous one from `DataAvailabilityAndDistribution` (which I've now fixed in the source).

So: documentation parser should use `description` from _referencing_ object if available, otherwise fall back to the general one from the _referenced_ object. So in the above `inclusionCriteria` should use its own description, not the one from `CohortCriteria`.

@mrueda this is yours or has this been handed off?

**Comment by mrueda** [comment]
@mbaudis parsing is on me. I'll take a look. Thx.

**Comment by mbaudis** [comment]
+1
