### ISSUE TITLE
example files in src directory have been translated into YAML

### ISSUE THREAD

**Issue by Tom-Shorter** [ga4gh-beacon/beacon-v2#7]
These should be in JSON format.

It might be worth moving the examples out of the `json` and `src` directories and into the the `framework` and `src` directories or possibly even into `root` to avoid duplication and to encourage the idea that using either yaml or json the final structure is the same.

**Comment by mbaudis** [comment]
Good idea - the best would probably be to have them in the documentation, not in the src / json at all. @mrueda ?

**Comment by jrambla** [comment]
The examples are in the repo/s to allow implementers to test/copy & paste, and whatever, without needing to go to any other source. I believe that added value still exists and I would be in favor of keeping them in the repo/s instead of moving them just to the documentation. If we want to replicate part/all of them in the documentation, I'm fine with that.

In the Model, the examples were inside every entrytype because, originally, I would like to allow implementers simply dropping the folders of those entrytypes they don't plan to implement and, hence, they don't need to go cherrypicking to every folder to have a coherent local instance of the Beacon. This added value is probably still valid, but I'm not so solid on that.

**Comment by mrueda** [comment]
With regards having the example in repos vs. documentation. I think we should keep them in the repos and programmatically include them in the documentation (I was thinking in displaying them with tabs underneath the default Models Markdown Tables). I already started this task.

Best,

m

**Comment by mbaudis** [comment]
+1 to @mrueda & @jrambla - closing this & moving w/ procedural refinements :-)
